# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::711356754645:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-O243CYP0QM0B
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::711356754645:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-13T13:36:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1641"
  uid: 192c8e65-4a83-4528-84a0-0a6aed5be7f5
